# Site settings
title:       abkolan
email:       abkolan+blog@gmail.com
author:      Abhilash Kolanthara
description: "Seek ! Therefore you are"
baseurl:     ""
url:         "http://abkolan.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: abkolan
stackoverflow_id: 64497
twitter_username: abkolan
google_plus_id:
linkedin_username: abhilashkolanthara
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
